(set-keyboard-coding-system nil)
(global-set-key [delete] 'delete-char)
(setq require-final-newline t)
(display-time)
(global-set-key (kbd "C-<tab>") 'other-window)
(global-set-key (kbd "C-l") 'goto-line)
(global-set-key (kbd "C-0") 'delete-window)
(global-set-key (kbd "M-S-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "M-S-<down>") 'enlarge-window)
(defun duplicate-line()
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (open-line 1)
  (next-line 1)
  (yank)
)
(defun copy-current-line()
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (move-beginning-of-line 1)
)
(global-set-key (kbd "C-p") 'copy-current-line)
(global-set-key (kbd "C-x C-d") 'duplicate-line)
(global-set-key (kbd "C-z") 'undo)




